'use strict';

export var finalWords = [
	'Let me tell you the whole story...',
	'Some time ago, someone decided to shift realities, to transcend their consciousness to a desired reality. This is called a Shifter.',
	'In doing so, they left behind a piece of consciousness in their current reality. A so-called Clone.',
	'Unbeknownst to the Shifter, their Clone decided to reality shift, leaving behind another piece of consciousness in their reality.',
	'Unbeknownst to <i>that</i> Clone, <i>their</i> Clone decided to reality shift, and another one, and so it went on.',
	'Somewhere along the line, one of these Clones started to feel lost. They started to see things we can not see.',
	'As if something was missing, the Clone went through their days feeling drawn to unknown places. They would have dreams about these places so real that they started to feel like memories. Memories of places they had visited.',
	'An ad for an online chat service came at the right time.',
	'Desperate to end the long lasting feeling of passivity and forever searching, they began the <i>Quest for the Self.</i>',
	'...',
	'After being interrupted during the Questionnaire conducted by the dubious Guide, the Clone found themself in an undefined space, seemingly with no borders and no boundaries.',
	'It felt familiar, like a memory.',
	'After some time, the sound of a voice from the other side filled the space.',
	'It explained how there were all these pieces of consciousness everywhere, that this was the reason the Clone had been feeling lost.',
	'That the pieces of consciousness were other Clones feeling the same way, that the images they had been seeing were the other Clones\' realities,',
	'the realities where they too had been seeing images from other places, as if they were dreams but must have been real.',
	'The voice, also a Clone, maybe the first one of them all, had spent all this time trying to collect themself, slowly, piece by piece.',
	'Once connected, they would finally have a sense of balance, their real and cloned selves would be the same.',
	'“I have come to deliver something you have lost.”',
	'“Follow me to find what you are searching for.”',
	'Can they be trusted?',
];
